name: Python Unit Test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.12

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python -m pytest test_cases.py



name: Validate Packer
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Packer Validate
        run: packer validate -syntax-only ami.pkr.hcl





name: Packer Deploy

on:
  pull_request:
   types: [closed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
        
    - name: Zip repository
      run: |
        mkdir -p dist
        git archive --format=zip HEAD -o dist/webapp.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-repo
        path: dist/webapp.zip

    - name: Packer Init
      run: packer init .

    - name: Configure AWS Credentials and build packer
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}

        

















  




