name: Packer Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Packers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
        
    - name: Zip repository
      run: |
        zip -r webapp.zip .

    - name: Packer Init
      run: packer init .

    - name: Configure AWS Credentials and build packer
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          
    - name: Packer Build
      run: |
        packer build ami.pkr.hcl